import Head from "next/head";
import Image from "next/image";
import React, { PropsWithChildren } from "react";
import { PortfolioNav } from "../nav/PortfolioNav";

interface IPropsWithChildrenProps extends PropsWithChildren {
  title?: string;
}

export const PageWrapper: React.FC<IPropsWithChildrenProps> = ({
  title,
  children,
}) => {
  return (
    <div className="bg-gray">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <PortfolioNav />

      <main className="min-h-screen">{children}</main>

      <footer className="p-8 bg-blue text-white">
        <p className="text-center"> Designed & Built by Alexander Bartolo</p>
      </footer>
    </div>
  );
};
