import Head from "next/head";
import Image from "next/image";
import React, { PropsWithChildren } from "react";

interface IPropsWithChildrenProps extends PropsWithChildren {
  title?: string;
}

export const PageWrapper: React.FC<IPropsWithChildrenProps> = ({
  title,
  children,
}) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-row justify-between items-center p-8">
        <Image
          loader={({ src }) => src}
          src="https://www.readygologos.com/wp-content/uploads/2018/01/AB-1.png"
          alt="Logo"
          width={50}
          height={52}
        />

        <nav>
          <a href="/html/">HTML</a> |<a href="/css/">CSS</a> |
          <a href="/js/">JavaScript</a> |<a href="/jquery/">jQuery</a>
        </nav>
      </header>

      <main className="min-h-screen bg-gray-300">{children}</main>

      <footer className="p-8 bg-gray-500 text-white">
        <p className="text-center"> Designed & Built by Alexander Bartolo</p>
      </footer>
    </div>
  );
};
