import Head from "next/head";
import Image from "next/image";
import React, { PropsWithChildren } from "react";

interface IPropsWithChildrenProps extends PropsWithChildren {
  title?: string;
}

export const PageWrapper: React.FC<IPropsWithChildrenProps> = ({
  title,
  children,
}) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children}</main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
              loader={({ src }) => {
                return src;
              }}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};
