name: Publish Artifact To Prod

# Controls when the workflow will run
on:  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      artifact:
        description: Artifact to upload
        required: true  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download_artifact:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{github.event.inputs.artifact}}

  # deploy:    
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --acl public-read --follow-symlinks --delete
  #       env:
  #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         # TODO: Figure out name
  #         AWS_REGION: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         SOURCE_DIR: '.next'
