name: Publish Artifact To Prod

# Controls when the workflow will run
on:  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      artifact:
        description: Artifact to upload
        required: true  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Download path
        run: mkdir ./build
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tag-artifact-creation.yml
          # name: ${{github.event.inputs.artifact}}
          name: test-v0.0.4-3011905428
          path: ./build

      - name: Upload files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ./build
          DEST_DIR: /artifact
